FROM openjdk:OPENJDK_VERSION

# Get android sdk, ndk, and rest of the stuff needed to build the android app.
ENV ANDROID_SDK_ROOT /usr/lib/android-sdk
ENV ANDROID_NDK_HOME $ANDROID_SDK_ROOT/ndk/ANDROID_NDK_VERSION
ENV PATH $ANDROID_SDK_ROOT/tools/bin:$PATH
ENV PATH $ANDROID_SDK_ROOT/build-tools/ANDROID_BUILD_TOOLS_VERSION:$PATH
ENV PATH $ANDROID_SDK_ROOT/platform-tools:$PATH
RUN set -o errexit -o nounset &&\
    echo "Downloading ANDROID SDK TOOLS" &&\
    curl -sO https://dl.google.com/android/repository/ANDROID_SDK_TOOLS_FILENAME &&\
    echo "Checking download hash" &&\
    echo 'ANDROID_SDK_TOOLS_CHECKSUM ANDROID_SDK_TOOLS_FILENAME' | sha256sum -c &&\
    echo "Installing ANDROID SDK TOOLS" &&\
    unzip -d $ANDROID_SDK_ROOT ANDROID_SDK_TOOLS_FILENAME &&\
    rm ANDROID_SDK_TOOLS_FILENAME &&\
    yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses &&\
    sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update &&\
    sdkmanager --sdk_root=$ANDROID_SDK_ROOT 'build-tools;ANDROID_BUILD_TOOLS_VERSION'

RUN echo ${OSTYPE}

LABEL maintainer="DockerWare.github.io" \
	  openjdk.version="OPENJDK_VERSION" \
	  gradle.version="GRADLE_VERSION" \
	  android.ndk.version="ANDROID_NDK_VERSION" \
	  android.sdk.tools.version="ANDROID_SDK_TOOLS_VERSION" \
	  go.version="GO_VERSION"
