FROM openjdk:15

# Get android sdk, ndk, and rest of the stuff needed to build the android app.
ENV ANDROID_SDK_ROOT /usr/lib/android-sdk
ENV ANDROID_NDK_HOME $ANDROID_SDK_ROOT/ndk/21.1.6352462
ENV PATH $ANDROID_SDK_ROOT/tools/bin:$PATH
ENV PATH $ANDROID_SDK_ROOT/build-tools/29.0.3:$PATH
ENV PATH $ANDROID_SDK_ROOT/platform-tools:$PATH
RUN set -o errexit -o nounset &&\
    echo "Downloading ANDROID SDK TOOLS" &&\
    curl -sO https://dl.google.com/android/repository/commandlinetools-win-6200805_latest.zip &&\
    echo "Checking download hash" &&\
    echo '8072ca0ad737eb3142793829a8682c685ae8a30a3b8f9b884fe8c617931af826 commandlinetools-win-6200805_latest.zip' | sha256sum -c &&\
    echo "Installing ANDROID SDK TOOLS" &&\
    unzip -d $ANDROID_SDK_ROOT commandlinetools-win-6200805_latest.zip &&\
    rm commandlinetools-win-6200805_latest.zip &&\
    yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses &&\
    sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update &&\
    sdkmanager --sdk_root=$ANDROID_SDK_ROOT 'build-tools;29.0.3' &&\
    sdkmanager --sdk_root=$ANDROID_SDK_ROOT 'platform-tools' &&\
    sdkmanager --sdk_root=$ANDROID_SDK_ROOT 'ndk;21.1.6352462'

RUN echo ${OSTYPE}

LABEL maintainer="DockerWare.github.io" \
	  openjdk.version="15" \
	  gradle.version="6.3" \
	  android.ndk.version="21.1.6352462" \
	  android.sdk.tools.version="6200805" \
	  go.version="1.14.2"
